### ISSUE TITLE
[Bug]: Python module fails to build on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [OpenJij/cimod#104]
### Contact Details

yuri@FreeBSD.org

### What happened?

```
===>  Building for py39-jij-cimod-1.4.36


--------------------------------------------------------------------------------
-- Trying "Ninja" generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
-- The C compiler identification is Clang 14.0.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is Clang 14.0.5
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying "Ninja" generator - success
--------------------------------------------------------------------------------

Configuring Project
  Working directory:
    /disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36/_skbuild/freebsd-13.1-STABLE-amd64-3.9/cmake-build
  Command:
    cmake /disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36/_skbuild/freebsd-13.1-STABLE-amd64-3.9/cmake-install/cimod -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3.9 -DPYTHON_VERSION_STRING:STRING=3.9.13 -DPYTHON_INCLUDE_DIR:PATH=/usr/local/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/usr/local/lib/libpython3.9.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/usr/local/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release

-- The C compiler identification is Clang 14.0.5
-- The CXX compiler identification is Clang 14.0.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake 3.23.3
-- Looking for a Fortran compiler
-- Looking for a Fortran compiler - /usr/local/bin/gfortran11
-- The Fortran compiler identification is GNU 11.3.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/local/bin/gfortran11 - skipped
-- We are on a FreeBSD system
-- The host processor is amd64
-- CMAKE_GENERATOR = Ninja
-- CIBUILDWHEEL = 
-- CMAKE_REQUIRE_FIND_PACKAGE_Eigen3 = 
-- CMAKE_REQUIRE_FIND_PACKAGE_nlohmann_json = 
-- CMAKE_REQUIRE_FIND_PACKAGE_pybind11 = 
-- CMAKE_REQUIRE_FIND_PACKAGE_pybind11_json = 
-- CMAKE_REQUIRE_FIND_PACKAGE_GTest = 
-- Started CMake for cimod 

-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /usr/local/lib/libopenblas.so  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- Found LAPACK: /usr/local/lib/libopenblas.so;-lm;-ldl  
-- Found OpenMP_C: -fopenmp=libomp (found version "5.0") 
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0") 
-- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "5.0")  
-- OMP_FOUND = YES
-- USE_OMP = ON
-- Skip Download eigen3
-- Found nlohmann_json: /usr/local/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found version "3.10.5") 
-- Skip Download nlohmann_json
CMake Error at CMakeLists.txt:161 (add_subdirectory):
  add_subdirectory given source "include" which is not an existing directory.


-- Build Python Extension.
-- Found Python: /usr/local/bin/python3.9 (found version "3.9.13") found components: Interpreter Development Development.Module Development.Embed 
'/usr/local/bin/python3.9' '-c' 'import pybind11; print(pybind11.get_cmake_dir())'
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Failed
-- Performing Test HAS_FLTO_THIN
-- Performing Test HAS_FLTO_THIN - Failed
-- Found pybind11: /usr/local/lib/python3.9/site-packages/pybind11/include (found version "2.10.0")
-- Could NOT find pybind11_json (missing: pybind11_json_DIR)
-- Downlod pybind11_json
-- Fetching Pybind11 Json
--   Populating pybind11_json
-- Configuring done
-- Generating done
-- Build files have been written to: /disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36/_skbuild/freebsd-13.1-STABLE-amd64-3.9/cmake-build/_deps/pybind11_json-subbuild
[1/9] Creating directories for 'pybind11_json-populate'
[1/9] Performing download step (git clone) for 'pybind11_json-populate'
Cloning into 'pybind11_json-src'...
HEAD is now at 1727c0b Release 0.2.12
[2/9] Performing update step for 'pybind11_json-populate'
[3/9] No patch step for 'pybind11_json-populate'
[5/9] No configure step for 'pybind11_json-populate'
[6/9] No build step for 'pybind11_json-populate'
[7/9] No install step for 'pybind11_json-populate'
[8/9] No test step for 'pybind11_json-populate'
[9/9] Completed 'pybind11_json-populate'
-- Fetching Pybind11 Json - fetched
-- Configuring incomplete, errors occurred!
See also "/disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36/_skbuild/freebsd-13.1-STABLE-amd64-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
See also "/disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36/_skbuild/freebsd-13.1-STABLE-amd64-3.9/cmake-build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 637, in setup
    env = cmkr.configure(
  File "/usr/local/lib/python3.9/site-packages/skbuild/cmaker.py", line 308, in configure
    raise SKBuildError(

An error occurred while configuring with CMake.
  Command:
    cmake /disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36/_skbuild/freebsd-13.1-STABLE-amd64-3.9/cmake-install/cimod -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3.9 -DPYTHON_VERSION_STRING:STRING=3.9.13 -DPYTHON_INCLUDE_DIR:PATH=/usr/local/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/usr/local/lib/libpython3.9.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/usr/local/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
  Source directory:
    /disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36
  Working directory:
    /disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36/_skbuild/freebsd-13.1-STABLE-amd64-3.9/cmake-build
Please see CMake's output for more information.
*** Error code 1

Stop.
```

### Python Version

3.9

### What os are you seeing the problem on?

Linux

### Relevant log output

```shell
$ cat /disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36/_skbuild/freebsd-13.1-STABLE-amd64-3.9/cmake-build/CMakeFiles/CMakeError.log
Determining if the Fortran sgemm exists failed with the following output:
Change Dir: /disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36/_skbuild/freebsd-13.1-STABLE-amd64-3.9/cmake-build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/ninja cmTC_7d237 && [1/4] Building Fortran preprocessed CMakeFiles/cmTC_7d237.dir/testFortranCompiler.f-pp.f
[2/4] Generating Fortran dyndep file CMakeFiles/cmTC_7d237.dir/Fortran.dd
[3/4] Building Fortran object CMakeFiles/cmTC_7d237.dir/testFortranCompiler.f.o
[4/4] Linking Fortran executable cmTC_7d237
FAILED: cmTC_7d237 
: && /usr/local/bin/gfortran11 -lpthread -lcblas -llapack -lpthread -Wl,-rpath=/usr/local/lib/gcc11  -L/usr/local/lib/gcc11 -B/usr/local/bin -fstack-protector-strong -L/usr/local/lib -O -Wl,-rpath=/usr/local/lib/gcc11 CMakeFiles/cmTC_7d237.dir/testFortranCompiler.f.o -o cmTC_7d237   && :
/usr/local/bin/ld: /usr/local/lib/libcblas.so: undefined reference to symbol 'sgemm_'
/usr/local/bin/ld: /usr/local/lib/libblas.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.



Performing C++ SOURCE FILE Test HAS_FLTO failed with the following output:
Change Dir: /disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36/_skbuild/freebsd-13.1-STABLE-amd64-3.9/cmake-build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/ninja cmTC_b7e50 && [1/2] Building CXX object CMakeFiles/cmTC_b7e50.dir/src.cxx.o
[2/2] Linking CXX executable cmTC_b7e50
FAILED: cmTC_b7e50 
: && /usr/bin/c++ -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -lpthread -lcblas -llapack -lpthread -Wl,-rpath=/usr/local/lib/gcc11  -L/usr/local/lib/gcc11 -B/usr/local/bin -fstack-protector-strong -L/usr/local/lib CMakeFiles/cmTC_b7e50.dir/src.cxx.o -o cmTC_b7e50  -flto && :
/usr/local/bin/ld: /usr/bin/../lib/LLVMgold.so: error loading plugin: Cannot open "/usr/bin/../lib/LLVMgold.so"
c++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.


Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test HAS_FLTO_THIN failed with the following output:
Change Dir: /disk-samsung/freebsd-ports/math/py-jij-cimod/work-py39/jij_cimod-1.4.36/_skbuild/freebsd-13.1-STABLE-amd64-3.9/cmake-build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/ninja cmTC_b68bd && [1/2] Building CXX object CMakeFiles/cmTC_b68bd.dir/src.cxx.o
[2/2] Linking CXX executable cmTC_b68bd
FAILED: cmTC_b68bd 
: && /usr/bin/c++ -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -lpthread -lcblas -llapack -lpthread -Wl,-rpath=/usr/local/lib/gcc11  -L/usr/local/lib/gcc11 -B/usr/local/bin -fstack-protector-strong -L/usr/local/lib CMakeFiles/cmTC_b68bd.dir/src.cxx.o -o cmTC_b68bd  -flto=thin && :
/usr/local/bin/ld: /usr/bin/../lib/LLVMgold.so: error loading plugin: Cannot open "/usr/bin/../lib/LLVMgold.so"
c++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.


Source file was:
int main() { return 0; }
```
```

**Comment by 29rou** [comment]
Perhaps these errors are generated when checking to see if the build environment is normal.
Unfortunately, I am not familiar with BSD and may not be able to help you solve this problem.
If possible, could you please PR me the code that can be built on BSD?
